package com.zjht.channel.manager.dao;

import com.zjht.channel.manager.model.Permission;
import com.zjht.channel.manager.model.PermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_permission
     *
     * @mbggenerated Thu Sep 17 21:08:20 CST 2015
     */
    int countByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_permission
     *
     * @mbggenerated Thu Sep 17 21:08:20 CST 2015
     */
    int deleteByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_permission
     *
     * @mbggenerated Thu Sep 17 21:08:20 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_permission
     *
     * @mbggenerated Thu Sep 17 21:08:20 CST 2015
     */
    int insert(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_permission
     *
     * @mbggenerated Thu Sep 17 21:08:20 CST 2015
     */
    int insertSelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_permission
     *
     * @mbggenerated Thu Sep 17 21:08:20 CST 2015
     */
    List<Permission> selectByExample(PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_permission
     *
     * @mbggenerated Thu Sep 17 21:08:20 CST 2015
     */
    Permission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_permission
     *
     * @mbggenerated Thu Sep 17 21:08:20 CST 2015
     */
    int updateByExampleSelective(@Param("record") Permission record, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_permission
     *
     * @mbggenerated Thu Sep 17 21:08:20 CST 2015
     */
    int updateByExample(@Param("record") Permission record, @Param("example") PermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_permission
     *
     * @mbggenerated Thu Sep 17 21:08:20 CST 2015
     */
    int updateByPrimaryKeySelective(Permission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_permission
     *
     * @mbggenerated Thu Sep 17 21:08:20 CST 2015
     */
    int updateByPrimaryKey(Permission record);
}