package com.zjht.channel.manager.dao;

import com.zjht.channel.manager.model.Security;
import com.zjht.channel.manager.model.SecurityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecurityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_security
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int countByExample(SecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_security
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int deleteByExample(SecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_security
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_security
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int insert(Security record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_security
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int insertSelective(Security record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_security
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    List<Security> selectByExample(SecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_security
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    Security selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_security
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int updateByExampleSelective(@Param("record") Security record, @Param("example") SecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_security
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int updateByExample(@Param("record") Security record, @Param("example") SecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_security
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int updateByPrimaryKeySelective(Security record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_security
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int updateByPrimaryKey(Security record);
}