package com.zjht.channel.manager.dao;

import com.zjht.channel.manager.model.Service;
import com.zjht.channel.manager.model.ServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_service
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int countByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_service
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int deleteByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_service
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_service
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int insert(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_service
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int insertSelective(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_service
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    List<Service> selectByExample(ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_service
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    Service selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_service
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int updateByExampleSelective(@Param("record") Service record, @Param("example") ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_service
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int updateByExample(@Param("record") Service record, @Param("example") ServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_service
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int updateByPrimaryKeySelective(Service record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_service
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int updateByPrimaryKey(Service record);
}