package com.zjht.channel.manager.dao;

import com.zjht.channel.manager.model.User;
import com.zjht.channel.manager.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_user
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    int updateByPrimaryKey(User record);
}