package com.zjht.channel.manager.model;

import java.util.Date;

import com.zjht.channel.manager.common.annotation.FieldSpecification;

public class Security {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_security.sec_id
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_security.sec_appno
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    @FieldSpecification(required=true,maxLength=16,name="终端号")
    private String appno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_security.sec_key
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    @FieldSpecification(required=true,maxLength=64,name="秘钥")
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_security.sec_name
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_security.sec_update_time
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_security.sec_remark
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_security.sec_id
     *
     * @return the value of channel_security.sec_id
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_security.sec_id
     *
     * @param id the value for channel_security.sec_id
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public Security setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_security.sec_appno
     *
     * @return the value of channel_security.sec_appno
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getAppno() {
        return appno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_security.sec_appno
     *
     * @param appno the value for channel_security.sec_appno
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setAppno(String appno) {
        this.appno = appno == null ? null : appno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_security.sec_key
     *
     * @return the value of channel_security.sec_key
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_security.sec_key
     *
     * @param key the value for channel_security.sec_key
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_security.sec_name
     *
     * @return the value of channel_security.sec_name
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_security.sec_name
     *
     * @param name the value for channel_security.sec_name
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_security.sec_update_time
     *
     * @return the value of channel_security.sec_update_time
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_security.sec_update_time
     *
     * @param updateTime the value for channel_security.sec_update_time
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_security.sec_remark
     *
     * @return the value of channel_security.sec_remark
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_security.sec_remark
     *
     * @param remark the value for channel_security.sec_remark
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}