package com.zjht.channel.manager.model;

import java.util.Date;

import com.zjht.channel.manager.common.annotation.FieldSpecification;

public class Service {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_service.svc_id
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_service.svc_owner
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    @FieldSpecification(required=true,name="负责人")
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_service.svc_organization
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    @FieldSpecification(required=true,name="组织名称")
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_service.svc_bean_id
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    @FieldSpecification(required=true,name="Bean Id")
    private String beanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_service.svc_fully_qualified_name
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    @FieldSpecification(required=true,name="服务接口全限定名")
    private String fullyQualifiedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_service.svc_name
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    @FieldSpecification(required=true,name="服务名称")
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_service.svc_version
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    @FieldSpecification(required=true,name="服务版本")
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_service.svc_status
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    @FieldSpecification(required=true,name="服务状态")
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_service.svc_update_time
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_service.svc_remark
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_service.svc_id
     *
     * @return the value of channel_service.svc_id
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_service.svc_id
     *
     * @param id the value for channel_service.svc_id
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public Service setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_service.svc_owner
     *
     * @return the value of channel_service.svc_owner
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_service.svc_owner
     *
     * @param owner the value for channel_service.svc_owner
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_service.svc_organization
     *
     * @return the value of channel_service.svc_organization
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_service.svc_organization
     *
     * @param organization the value for channel_service.svc_organization
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_service.svc_bean_id
     *
     * @return the value of channel_service.svc_bean_id
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getBeanId() {
        return beanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_service.svc_bean_id
     *
     * @param beanId the value for channel_service.svc_bean_id
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setBeanId(String beanId) {
        this.beanId = beanId == null ? null : beanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_service.svc_fully_qualified_name
     *
     * @return the value of channel_service.svc_fully_qualified_name
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getFullyQualifiedName() {
        return fullyQualifiedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_service.svc_fully_qualified_name
     *
     * @param fullyQualifiedName the value for channel_service.svc_fully_qualified_name
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setFullyQualifiedName(String fullyQualifiedName) {
        this.fullyQualifiedName = fullyQualifiedName == null ? null : fullyQualifiedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_service.svc_name
     *
     * @return the value of channel_service.svc_name
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_service.svc_name
     *
     * @param name the value for channel_service.svc_name
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_service.svc_version
     *
     * @return the value of channel_service.svc_version
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_service.svc_version
     *
     * @param version the value for channel_service.svc_version
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_service.svc_status
     *
     * @return the value of channel_service.svc_status
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_service.svc_status
     *
     * @param status the value for channel_service.svc_status
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_service.svc_update_time
     *
     * @return the value of channel_service.svc_update_time
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_service.svc_update_time
     *
     * @param updateTime the value for channel_service.svc_update_time
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_service.svc_remark
     *
     * @return the value of channel_service.svc_remark
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_service.svc_remark
     *
     * @param remark the value for channel_service.svc_remark
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}