package com.zjht.channel.manager.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.user_id
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.user_name
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.user_password
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.user_update_time
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_user.user_remark
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.user_id
     *
     * @return the value of channel_user.user_id
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.user_id
     *
     * @param id the value for channel_user.user_id
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.user_name
     *
     * @return the value of channel_user.user_name
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.user_name
     *
     * @param name the value for channel_user.user_name
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.user_password
     *
     * @return the value of channel_user.user_password
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.user_password
     *
     * @param password the value for channel_user.user_password
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.user_update_time
     *
     * @return the value of channel_user.user_update_time
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.user_update_time
     *
     * @param updateTime the value for channel_user.user_update_time
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_user.user_remark
     *
     * @return the value of channel_user.user_remark
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_user.user_remark
     *
     * @param remark the value for channel_user.user_remark
     *
     * @mbggenerated Thu Sep 17 16:16:46 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}